# Generated by Django 5.0.3 on 2024-04-21 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogstories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogstories',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='blogstories',
            name='country',
            field=models.CharField(default='Tbilisi', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogstories',
            name='img',
            field=models.ImageField(max_length=2000, upload_to=None),
        ),
        migrations.CreateModel(
            name='BlogDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=2000, upload_to=None)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
